# Generated by Django 2.0.2 on 2018-07-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180719_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='link',
        ),
    ]
